version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
      # environment variables for all commands executed in the primary container
        environment:
          GIT_AUTHOR_NAME: circleci
          GIT_AUTHOR_EMAIL: noreply@circleci.com
          GIT_COMMITTER_NAME: circleci
          GIT_COMMITTER_EMAIL: noreply@circleci.com
          EMAIL: noreply@circleci.com

    working_directory: ~/autosemver

    environment:
      JVM_OPTS: -Xmx2048m
      TERM: dumb

    steps:
      - add-ssh-keys:
         fingerprints:
           - "c9:3d:45:20:5c:62:04:83:81:c2:5f:df:73:46:79:f3"
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # publishModules will take effect only when the current branch is configured in the root project's build.gradle
      - run: ./gradlew clean test bumpVersion

      - store_artifacts:
          path: core/build/reports
          destination: core/reports
      - store_artifacts:
          path: git/build/reports
          destination: git/reports

      - deploy:
          name: deploy to bintray
          command: |
            if [ "$CIRCLE_BRANCH" == "alpha" ] || [ "$CIRCLE_BRANCH" == "beta" ] || [ "$CIRCLE_BRANCH" == "master" ]; then
              ./gradlew publishModules
            fi
