version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha

    working_directory: ~/autosemver

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx2048m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew clean test

      - store_artifacts:
          path: core/build/reports
          destination: core/reports
      - store_artifacts:
          path: git/build/reports
          destination: git/reports

      - deploy:
          name: deploy to bintray
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              ./gradlew bumpVersion publishModules
            elif [ "$CIRCLE_BRANCH" == "integration" ]; then
              ./gradlew bumpVersion
              echo "would be deploying snapshot somewhere"
            fi
