version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha

    working_directory: ~/autosemver

    environment:
      JVM_OPTS: -Xmx2048m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: ./gradlew dependencies

      - run: which git
      - run: git rev-parse --abbrev-ref HEAD

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # publishModules will take effect only when the current branch is configured in the root project's build.gradle
      - run: ./gradlew clean test bumpVersion

      - store_artifacts:
          path: core/build/reports
          destination: core/reports
      - store_artifacts:
          path: git/build/reports
          destination: git/reports

      - deploy:
          name: deploy to bintray
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              ./gradlew publishModules
            fi
